### ISSUE TITLE
link suggestions don't find all links

### ISSUE THREAD

**Issue by jonsterling** [Trebor-Huang/vscode-forester#1]
I am finding that only a small fraction of my trees are being presented as link suggestions. I have verified that I am querying the correct directories in the extension settings. Please let me know if there's anything I can do to help reproduce this issue.

**Comment by Trebor-Huang** [comment]
Hmm, does the json dump contain the entries you want? If so it's probably some suggestion number cap of VSCode. I'll dig the documentation and see if there's anything..

**Comment by jonsterling** [comment]
Yes, when I run the command `forester query` command that the extension is configured with, all the trees are dumped. What I am finding is that almost none of my trees except the bibliographic ones are being suggested by the extension, however.

**Comment by Trebor-Huang** [comment]
I can't reproduce this even with 10000 trees. Could you provide the dumped json with sensitive information removed? A reproducing `trees` directory is even better.

**Comment by jonsterling** [comment]
I will double check when I get a chance, but it should be possible to reproduce this with my public forest: http://github.com/jonsterling/forest .

**Comment by Trebor-Huang** [comment]
OK I can reproduce consistently, but not in the debug environment?? Maybe there is a VSCode behavior change in debug mode

**Comment by Trebor-Huang** [comment]
Found it. There is an untitled tree that happens to sit at the 101st position! VSCode deals with a `null` entry by truncating the list there. This was such a whole number that I thought it is a fixed upper bound in length, and by fixing this the problem is gone. Typescript didn't catch that because there isn't a JSON scheme ready :(

**Comment by Trebor-Huang** [comment]
I'll publish a patch version, please let me know whether the problem persists!

**Comment by jonsterling** [comment]
It's working well for me now, thanks!!
