### ISSUE TITLE
Completion for typing in tree IDs

### ISSUE THREAD

**Issue by jonsterling** [Trebor-Huang/vscode-forester#4]
It would be great if the link suggestions would _also_ match tree IDs in addition to titles. As hard as it is to imagine, I have wired my brain to know the addresses of many trees in my forest, and so I am more often typing in the address than I am typing in the title; what would be amazing is if I could see suggestions while doing that, and it would preview the title, etc.

**Comment by Trebor-Huang** [comment]
Yes that's doable. I can make the filter act on both the address and title, and the suggestion only shows the title and taxon (because we only have so much space). Would that be good?

**Comment by jonsterling** [comment]
Thanks for doing this! It works well. I understand there is limited space, but I wonder if there could be a configuration that shows the tree-id first. One thing I find is that if tree IDs are shown, it will assist one's brain to memorise the tree IDs (solidifying partial memory of tree IDs).
