### ISSUE TITLE
Completion when there's a lot of trees is slow

### ISSUE THREAD

**Issue by Trebor-Huang** [Trebor-Huang/vscode-forester#5]
Can we do the stream thing and add to the list asynchronously?

**Comment by Trebor-Huang** [comment]
We can rescan only when the workspace has filesystem change events

**Comment by Trebor-Huang** [comment]
Javascript promise is so weird

**Comment by Trebor-Huang** [comment]
Forester somehow outputs error messages in stdout (the default of asai).

**Comment by kentookura** [comment]
I suspect making use of the forester errors in our plugins requires some changes to forester.   I also think it's time to make the error messages available in json.

**Comment by jonsterling** [comment]
Let me tag @Favonia.

**Comment by Trebor-Huang** [comment]
asai has the option to output to stderr, and to remove the fancy dressing. So a commandline option to forester should suffice

**Comment by jonsterling** [comment]
It seems like these are two separate things — shouldn't warnings and errors always go to stderr no matter what? If it is currently going to stdout, that should probably be corrected regardless of the tooling issues. And we could provide an option to remove the fancy dressing separately. sound reasonable?

**Comment by Trebor-Huang** [comment]
This discussion is somewhat unrelated to the issue, which I closed because I implemented a rate-limited scanning triggered by filesystem changes. Now operating a large forest should be relatively fast.
