### ISSUE TITLE
Update for new command line interface

### ISSUE THREAD

**Issue by jonsterling** [Trebor-Huang/vscode-forester#6]
Forester's command line interface is changing, as discussed in this ticket: https://todo.sr.ht/~jonsterling/forester/44#event-339153
Once this change gets packaged into a release of forester (hopefully soon), we can release a new version of the VS Code extension.

**Comment by Trebor-Huang** [comment]
It's ready to release. Although we should definitely have a better mechanism to sync forester with the vscode plugin somehow..
