### ISSUE TITLE
Extension not working as expected

### ISSUE THREAD

**Issue by rayruitang** [Trebor-Huang/vscode-forester#8]
I added the path to the forester as `/Users/username/.opam/default/bin/forester` in the extension setting. However, after choosing the prefix there is no tree created. Also, how do I set the path where the trees are created?

Thanks a lot!

**Comment by Trebor-Huang** [comment]
You choose the path by simply right clicking the folder in which you want to create your tree. I couldn't really do anything unless you have more detailed reproduction instructions or logs. You can use the command palette to show logs for the extension host.

**Comment by rayruitang** [comment]
Thanks. After looking at the log, it reminds me that I should have a directory called template, which I never knew I should've done.
After creating one, it works fine.

**Comment by rayruitang** [comment]
Thanks. After looking at the log, it reminds me that I should have a directory called template, which I never knew I should've done.
After creating one, it works fine.

**Comment by Trebor-Huang** [comment]
Is this not automatically set up by `forester init`?
